name: build
on: [push, pull_request]
env:
  CI: true
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
      - name: Install
        run: |
          npm install
      - name: Test
        run: npm build